# Site settings
title: Alberto Montellano Sandoval
twitter_username: amsdec
name: Alberto Montellano Sandoval

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://amontellano.blogspot.com/
 - title: GitHub
   url: https://github.com/amsdec
 - title: LinkedIn
   url: https://mx.linkedin.com/in/albertomontellano

#Any buzzword skills you want to include
skills:
 - Python
 - Spring MVC
 - Java
 - JPA
 - SQL
 - REST
 - Tech Architecture
 - jQuery
 - XML

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: http://amontellano.blogspot.com/feeds/posts/default

#Work experience is required
roles:
 - title: Ingeniero de Software
   start: 2016
   end: Actual
   employer: TCPIP
   description: Desarrollo de producto de reservaciones de boletos para aerolineas.
 - title: Gerente de desarrollo
   start: 2008
   end: 2016
   employer: Tralix
   description: Desarrollo de apliaciones de facturación electrónica e email marketing de alta disponibilidad y resistente a fallos para soporte a servicios ofrecidos por la empresa. Enrolado también en actividades de administración del equipo de desarrollo.
 - title: Ingeniero de Software
   start: 2006
   end: 2008
   employer: OpenRoad
   description: Modificaciones a software de distintos canales de comunicación con el cliente final para empresas del sector financiero.

#Education is required
education:
 - level: Ingeniero en sistemas computacionales
   date: 2006
   subject: Bases de datos
   school: Instituto Tecnológico de Querétaro

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/0ac17c4f1ea5b664e631fee0e242c275
   courses:
    - title: Functional Programming Principles in Scala
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: September, 2014
    - title: Programming Mobile Applications for Android Handheld Systems
      link: https://www.coursera.org/course/android
      optionalimage: https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-course-photos.s3.amazonaws.com/5c/9fcef0feaa11e49d7ccbc529516477/Screen-Shot-2015-05-19-at-9.40.26-PM.png?auto=format&dpr=2&w=200&h=112&fit=crop
      date: Junio, 2014

#List of interesting Github repo/projects to include - optional
github:
 - amsdec/pythonHtmlScraping
 - amsdec/vendingMachine
 - amsdec/intersectionPoint
 - amsdec/fibonacci
 - amsdec/numerosPrimos
 - amsdec/TicTacToe
 - amsdec/GameOfLife

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Agil</strong>: Soy creyente y practico los valores del agilismo, así como sus rituales y mejores prácticas, creo en las personas y en que con una gran motivacion pueden explotar al máximo sus capacidades.
   <strong>Management 3.0</strong>: Durante mi tiempo como lider de equipo y gerente llevé acabo algúnas prácticas relacionadas con management 3.0, entre ellas el hehco de que el equipo decida lo más que se pueda lo relacionado a él mismo.
   <strong>Ciclo de vida del desarrollo</strong>: Entiendo y he estado en tareas de entregas contínuas implementando pipelines desde el inicio del proyect hasta el despliegue pasando por pruebas automatizadas.
